/*import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
*/

const Index = () => {
  return (
    <div className="container px-4 px-lg-5">
      <div className="row gx-4 gx-lg-5 justify-content-center">
        <div className="col-md-10 col-lg-8 col-xl-7">
          {/*<!-- Post preview-->*/}
          <div className="post-preview">
            <a href="post.html">
              <h2 className="post-title">
                Man must explore, and this is exploration at its greatest
              </h2>
              <h3 className="post-subtitle">
                Problems look mighty small from 150 miles up
              </h3>
            </a>
            <p className="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on September 24, 2021
            </p>
          </div>
          {/*<!-- Divider-->*/}
          <hr className="my-4" />
          {/*<!-- Post preview-->*/}
          <div className="post-preview">
            <a href="post.html">
              <h2 className="post-title">
                I believe every human has a finite number of heartbeats. I don't
                intend to waste any of mine.
              </h2>
            </a>
            <p className="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on September 18, 2021
            </p>
          </div>
          {/*<!-- Divider-->*/}
          <hr className="my-4" />
          {/*<!-- Post preview-->*/}
          <div className="post-preview">
            <a href="post.html">
              <h2 className="post-title">
                Science has not yet mastered prophecy
              </h2>
              <h3 className="post-subtitle">
                We predict too much for the next year and yet far too little for
                the next ten.
              </h3>
            </a>
            <p className="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on August 24, 2021
            </p>
          </div>
          {/*<!-- Divider-->*/}
          <hr className="my-4" />
          {/*<!-- Post preview-->*/}
          <div className="post-preview">
            <a href="post.html">
              <h2 className="post-title">Failure is not an option</h2>
              <h3 className="post-subtitle">
                Many say exploration is part of our destiny, but it’s actually
                our duty to future generations.
              </h3>
            </a>
            <p className="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on July 8, 2021
            </p>
          </div>
          {/*<!-- Divider-->*/}
          <hr className="my-4" />
          {/*<!-- Pager-->*/}
          <div className="d-flex justify-content-end mb-4">
            <a className="btn btn-primary text-uppercase" href="#!">
              Older Posts →
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Index;
